services:
  # A Docker web service
  - type: web
    name: lambda-backend
    runtime: python
    plan: free
    autoDeploy: false
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn server:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: GEMINI_API_KEY
        sync: false
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_ANON_KEY
        sync: false
      - key: MENTOR_SYSTEM_INSTRUCTION
        sync: false
      - key: EXERCISE_SYSTEM_INSTRUCTION
        sync: false